# Setup
title:        Muhammad Abdul WAHAB (Personal page)
tagline:      PhD Student at CentraleSupélec 
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Muhammad Abdul WAHAB
  url:        https://mawahab.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
