# Site settings
title: Muhammad Abdul Wahab
header-img: img/home-bg.jpg
email: abdulparis@gmail.com
copyright_name: 
description: "PhD Student CentraleSupélec/IETR"
baseurl: ""
url: "http://mawahab.github.io"
twitter_username: MAbdulwahabp
github_username:  mawahab
facebook_username:  abdulparis
email_username:  abdulparis@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
